sudo: required
language: php

matrix:
  include:
  - php: '7.1'
    env: SWOOLE_VERSION="a8d92fcba8d276cb5083a888f60d021b84d98775"
  - php: '7.1'
    env: SWOOLE_VERSION="ba159e64729f117da0781d3f3c5eac0d533d3fb3"
  - php: '7.1'
    env: SWOOLE_VERSION="c6af70405081c4752059b546a4364cacf042b5e4"
  - php: '7.1'
    env: SWOOLE_VERSION="40b161803ab9268df7edc7eabc8f5627da4d6660"
  - php: '7.1'
    env: SWOOLE_VERSION="89227aeeb63b3b51de7af690bca59854364f34dd"
  - php: '7.1'
    env: SWOOLE_VERSION="c57b6c7bc51e25b43578ef83538b16bb755009fc"
  - php: '7.1'
    env: SWOOLE_VERSION="92bf3cfd653bc04aaee1390f8e556387450d9efc"
  - php: '7.1'
    env: SWOOLE_VERSION="6b6c5cc7b6cb2881ed6a9f9184073584c094e785"

services:
  - redis-server
  - mysql

addons:
  apt:
    packages:
    - unzip
    - nginx

install:
  - if [[ $INSTALL_REDIS_EXT == true ]]; then
      wget https://github.com/phpredis/phpredis/archive/develop.zip;
      unzip develop.zip;
      cd phpredis-develop;
      phpize;
      ./configure;
      make && make install;
      cd ../;
    fi
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure && make -j && make install && cd -
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - sudo cp $TRAVIS_BUILD_DIR/.travis/default.vhost /etc/nginx/sites-available/default.vhost
  - sudo ln -s /etc/nginx/sites-available/default.vhost /etc/nginx/sites-enabled/default.vhost
  - sudo service nginx reload
  - if [[ $DISABLE_XDEBUG != false ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - sh tests/db/install-db.sh
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - export TEST_PHPUNIT_PATH=~/.phpenv/versions/$(phpenv version-name)/bin/phpunit
  - composer update
  - cd ./tests && composer update && cd ../
  - php --ri swoole

script:
  - ./tests/phpunit -c ./tests/phpunit.xml

after_failure:
  - php ./.travis/output-server-log.php

env:
  global:
    - MYSQL_SERVER_USERNAME: root
    - MYSQL_SERVER_PASSWORD:
    - HTTP_SERVER_HOST: http://127.0.0.1:13010/
    - HTTP_SESSION_TEST_SERVER_HOST: http://127.0.0.1:13015/
